// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "ReGuid.1037aad6-42ae-43db-a802-93991c0bbc7c";
        public const string Name = "ReGuid";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Brent Seger";
        public const string Tags = "";
    }
}
