// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReGuid
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ReGuidString = "af3a5da6-0076-4bdb-b25e-ab65c1fb7b81";
        public static Guid ReGuid = new Guid(ReGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ReGuidMenuGroup = 0x0001;
        public const int InsertGuidCommand = 0x0100;
        public const int ReplaceGuidsCommand = 0x0101;
    }
}